In [2]:
import pandas as pd
import re
import ifcopenshell

# CSV ファイルのパス
csv_path = r"C:\Users\Owner\Documents\25952501_RioSaijo\IFC2RDF_Fork\data\resources\BDNS_Abbreviations_Register _v2.1.3.csv"

# CSV の読み込み
df = pd.read_csv(csv_path)

# データ構造の確認
df.head()

,asset_description,asset_abbreviation,can_be_connected,dbo_entity_type,ifc4_3,ifc2x3,is_ifc_default
0,access control - RFID controller,RFIDC,1,NaN,IfcController,IfcController,0
1,access control - RFID reader,RFIDR,1,NaN,IfcCommunicationsApplianceSCANNER,IfcElectricApplianceSCANNER,0
2,access control - access control system,ACS,1,NaN,IfcDistributionSystemSECURITY,NaN,0
3,access control - audio intercom,AIC,1,NaN,IfcSwitchingDevice,IfcSwitchingDevice,0
4,access control - biometric reader,BIOR,1,NaN,IfcCommunicationsApplianceSCANNER,IfcElectricApplianceSCANNER,0

In [6]:
#Entity と PredefinedType を分解する関数定義
def split_ifc_entity_and_type(value):
    if pd.isna(value):
        return pd.Series([None, None])

    value = str(value)

    match = re.match(r"^(Ifc[A-Za-z0-9]+?)([A-Z]+)$", value)

    if match:
        entity = match.group(1)
        predefined_type = match.group(2)
        return pd.Series([entity, predefined_type])
    else:
        return pd.Series([value, None])

In [7]:
df[["ifc2x3_entity", "ifc2x3_predefined_type"]] = (
    df["ifc2x3"]
    .apply(split_ifc_entity_and_type)
)

df[["ifc2x3", "ifc2x3_entity", "ifc2x3_predefined_type"]].head()

                        ifc2x3         ifc2x3_entity ifc2x3_predefined_type
0                IfcController         IfcController                    NaN
1  IfcElectricApplianceSCANNER  IfcElectricAppliance                SCANNER
2                          NaN                   NaN                    NaN
3           IfcSwitchingDevice    IfcSwitchingDevice                    NaN
4  IfcElectricApplianceSCANNER  IfcElectricAppliance                SCANNER

In [8]:
df[["ifc4_3_entity", "ifc4_3_predefined_type"]] = (
    df["ifc4_3"]
    .apply(split_ifc_entity_and_type)
)

df[["ifc4_3", "ifc4_3_entity", "ifc4_3_predefined_type"]].head()

,ifc4_3,ifc4_3_entity,ifc4_3_predefined_type
0,IfcController,IfcController,NaN
1,IfcCommunicationsApplianceSCANNER,IfcCommunicationsAppliance,SCANNER
2,IfcDistributionSystemSECURITY,IfcDistributionSystem,SECURITY
3,IfcSwitchingDevice,IfcSwitchingDevice,NaN
4,IfcCommunicationsApplianceSCANNER,IfcCommunicationsAppliance,SCANNER

In [9]:
df

,asset_description,asset_abbreviation,can_be_connected,dbo_entity_type,ifc4_3,ifc2x3,is_ifc_default,ifc2x3_entity,ifc2x3_predefined_type,ifc4_3_entity,ifc4_3_predefined_type
0,access control - RFID controller,RFIDC,1,NaN,IfcController,IfcController,0,IfcController,NaN,IfcController,NaN
1,access control - RFID reader,RFIDR,1,NaN,IfcCommunicationsApplianceSCANNER,IfcElectricApplianceSCANNER,0,IfcElectricAppliance,SCANNER,IfcCommunicationsAppliance,SCANNER
2,access control - access control system,ACS,1,NaN,IfcDistributionSystemSECURITY,NaN,0,NaN,NaN,IfcDistributionSystem,SECURITY
3,access control - audio intercom,AIC,1,NaN,IfcSwitchingDevice,IfcSwitchingDevice,0,IfcSwitchingDevice,NaN,IfcSwitchingDevice,NaN
4,access control - biometric reader,BIOR,1,NaN,IfcCommunicationsApplianceSCANNER,IfcElectricApplianceSCANNER,0,IfcElectricAppliance,SCANNER,IfcCommunicationsAppliance,SCANNER
...,...,...,...,...,...,...,...,...,...,...,...
931,water treatment - dosing pot,DPOT,0,NaN,IfcTank,IfcTank,0,IfcTank,NaN,IfcTank,NaN
932,water treatment - electro magnetic water condi...,EMWC,0,NaN,IfcFilterWATERFILTER,IfcFilterWATERFILTER,0,IfcFilter,WATERFILTER,IfcFilter,WATERFILTER
933,weather station,WST,1,HVAC/WEATHER,IfcUnitaryControlElementWEATHERSTATION,IfcElectricDistributionPoint,0,IfcElectricDistributionPoint,NaN,IfcUnitaryControlElement,WEATHERSTATION
934,window,WD,0,NaN,IfcWindow,IfcWindowStyle,1,IfcWindowStyle,NaN,IfcWindow,NaN
935,zone,ZONE,1,NaN,IfcZone,IfcZone,1,IfcZone,NaN,IfcZone,NaN

In [10]:
df.to_csv(r"C:\Users\Owner\Documents\25952501_RioSaijo\IFC2RDF_Fork\data\resources\BDNS_Abbreviations_Register _v2.1.3_curated.csv", index=False)